// helper/coursesTwo/coursesTwoData.js

export const coursesTwoData = [
  {
    id: 1,
    slug: "language-class",
    title: "Language Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/language-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher1.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 50,
  },
  {
    id: 2,
    slug: "drawing-class",
    title: "Drawing Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/drawing-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher2.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 50,
  },
  {
    id: 3,
    slug: "mathematics-class",
    title: "Mathematics Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/mathematics-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 50,
  },
  {
    id: 4,
    slug: "web-design-class",
    title: "Web Design Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/web-design-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher1.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 80,
  },
  {
    id: 5,
    slug: "html-development-class",
    title: "HTML Development Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/html-development-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher2.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 50,
  },
  {
    id: 6,
    slug: "digital-marketing-class",
    title: "Digital Marketing Class",
    description: "Seamlessly visualize quality ellectual capital without superior collaboration and idea.",
    image: "/images/coursesTwo/digital-marketing-class.jpg",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Robto Jone",
      role: "Teacher",
    },
    rating: 4,
    age: "5-10 Years",
    time: "8-10am",
    classSize: 28,
    fee: 50,
  },
];