export const coursesTwoDetailsData = [
  {
    slug: "language-class",
    title: "The Language Class Course",
    image: "/images/coursesTwo/language-class.webp",
    price: 59,
    originalPrice: 139,
    instructor: "Robto Jone",
    lectures: 12,
    duration: "4 weeks",
    enrolled: 28,
    language: "English",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Robto Jone",
      role: "Teacher",
      category: "Language",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis et quasi architects beatae vitae dicta sunt explicabo.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future. As the only university where a renowned design school comes together with premier colleges, we are making learning more relevant and transformational.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
      },
    ],
  },
  {
    slug: "drawing-class",
    title: "The Drawing Class Course",
    image: "/images/coursesTwo/drawing-class.jpg",
    price: 49,
    originalPrice: 99,
    instructor: "Anna Smith",
    lectures: 10,
    duration: "3 weeks",
    enrolled: 20,
    language: "English",
    teacher: {
      avatar: "/images/coursesTeacher/teacher2.webp",
      name: "Anna Smith",
      role: "Teacher",
      category: "Arts",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing.",
      },
    ],
  },
  {
    slug: "mathematics-class",
    title: "The Mathematics Class Course",
    image: "/images/coursesTwo/mathematics-class.webp",
    price: 69,
    originalPrice: 149,
    instructor: "John Doe",
    lectures: 16,
    duration: "8 weeks",
    enrolled: 35,
    language: "English",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "John Doe",
      role: "Teacher",
      category: "Mathematics",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing.",
      },
    ],
  },
  {
    slug: "web-design-class",
    title: "The Web Design Class Course",
    image: "/images/coursesTwo/web-design-class.webp",
    price: 79,
    originalPrice: 159,
    instructor: "Sara Khan",
    lectures: 18,
    duration: "6 weeks",
    enrolled: 40,
    language: "English",
    teacher: {
     avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Sara Khan",
      role: "Teacher",
      category: "Design",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing.",
      },
    ],
  },
  {
    slug: "html-development-class",
    title: "The HTML Development Class Course",
    image: "/images/coursesTwo/html-development-class.webp",
    price: 59,
    originalPrice: 119,
    instructor: "Mike Lee",
    lectures: 14,
    duration: "5 weeks",
    enrolled: 30,
    language: "English",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Mike Lee",
      role: "Teacher",
      category: "Development",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing.",
      },
    ],
  },
  {
    slug: "digital-marketing-class",
    title: "The Digital Marketing Class Course",
    image: "/images/coursesTwo/digital-marketing-class.webp",
    price: 89,
    originalPrice: 179,
    instructor: "Lisa Ray",
    lectures: 20,
    duration: "10 weeks",
    enrolled: 50,
    language: "English",
    teacher: {
      avatar: "/images/coursesTeacher/teacher3.webp",
      name: "Lisa Ray",
      role: "Teacher",
      category: "Marketing",
    },
    overview: [
      "Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis.",
      "The world of search engine optimization is complex and ever-changing, but you can easily understand the basics.",
    ],
    whatYouWillLearn: [
      "Crawl accessibility so engines can read your website",
      "Share-worthy content that earns links, citations",
      "Keyword optimized to attract searchers & engines",
      "Title, URL & description to draw high CTR",
    ],
    studyOptions: [
      { qualification: "Bsc (Hons)", length: "3 years full time", code: "CDX3" },
      { qualification: "Bsc", length: "4 years full time", code: "CDX4" },
    ],
    faq: [
      {
        id: 1,
        question: "01 Cras turpis felis, elementum sed mi at arcu?",
        answer: "Our community is being called to reimagine the future.",
      },
      {
        id: 2,
        question: "02 Vestibulum nibh risus, in neque eleifendulputate sem?",
        answer: "Lorem ipsum is simply free text used by copytyping refreshing.",
      },
      {
        id: 3,
        question: "03 Donec maximus, sapien id auctor ornare?",
        answer: "The world of search engine optimization is complex and ever-changing.",
      },
    ],
  },
];