const courses = [
  {
    id: 1,
    image: "/images/courses/ai.webp",
    category: "Computer Science",
    title: "BSc in Artificial Intelligence",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "On Campus",
    rating: 4.8,
    reviews: 126,
    students: 320,
  },
  {
    id: 2,
    image: "/images/courses/mba.webp",
    category: "Business",
    title: "Master of Business Administration",
    duration: "2 Years",
    level: "Postgraduate",
    mode: "On Campus",
    rating: 4.9,
    reviews: 214,
    students: 480,
  },
  {
    id: 3,
    image: "/images/courses/biotech.webp",
    category: "Biotechnology",
    title: "BSc in Biotechnology",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "On Campus",
    rating: 4.7,
    reviews: 98,
    students: 260,
  },
  {
    id: 4,
    image: "/images/courses/civil.webp",
    category: "Engineering",
    title: "BSc in Civil Engineering",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "On Campus",
    rating: 4.8,
    reviews: 178,
    students: 410,
  },
  {
    id: 5,
    image: "/images/courses/law.webp",
    category: "Law",
    title: "Bachelor of Law (LLB)",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "On Campus",
    rating: 4.9,
    reviews: 142,
    students: 300,
  },
  {
    id: 6,
    image: "/images/courses/data-science.webp",
    category: "Data Science",
    title: "BSc in Data Science",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "Hybrid",
    rating: 4.9,
    reviews: 235,
    students: 540,
  },
  {
    id: 7,
    image: "/images/courses/graphic-design.webp",
    category: "Design",
    title: "Graphic Design & UI/UX",
    duration: "1 Year",
    level: "Professional",
    mode: "Online",
    rating: 4.8,
    reviews: 189,
    students: 690,
  },
  {
    id: 8,
    image: "/images/courses/education.webp",
    category: "Education",
    title: "Bachelor of Education",
    duration: "4 Years",
    level: "Undergraduate",
    mode: "On Campus",
    rating: 4.6,
    reviews: 88,
    students: 210,
  },
  {
    id: 9,
    image: "/images/courses/finance.webp",
    category: "Finance",
    title: "Finance & Accounting",
    duration: "3 Years",
    level: "Diploma",
    mode: "Online",
    rating: 4.8,
    reviews: 163,
    students: 450,
  },
];

export default courses;