const courses = [
  {
    id: 1,
    slug: "biochemistry",
    title: "Biochemistry",
    category: "Graduate Programs",
    image: "/images/courses/biochemistry.jpg",
    instructor: "Dr. Sarah Johnson",
    duration: "2 Years",
    students: 120,
    rating: 4.8,
    price: 1200,
    description: "Explore the chemical processes within living organisms. This program covers molecular biology, genetics, and metabolic pathways.",
  },
  {
    id: 2,
    slug: "major-in-economics",
    title: "Major in Economics",
    category: "Graduate Programs",
    image: "/images/courses/economics.jpg",
    instructor: "Prof. Michael Brown",
    duration: "3 Years",
    students: 200,
    rating: 4.7,
    price: 1500,
    description: "Develop a deep understanding of economic theory, policy analysis, and quantitative research methods.",
  },
  {
    id: 3,
    slug: "business-media",
    title: "Business Media",
    category: "Graduate Programs",
    image: "/images/courses/business-media.jpg",
    instructor: "Dr. Emily Clark",
    duration: "2 Years",
    students: 180,
    rating: 4.9,
    price: 1800,
    description: "Combine business strategy with media communications to lead in the modern digital economy.",
  },
  {
    id: 4,
    slug: "public-administration",
    title: "Public Administration",
    category: "Graduate Programs",
    image: "/images/courses/public-admin.jpg",
    instructor: "Prof. David Wilson",
    duration: "2 Years",
    students: 150,
    rating: 4.6,
    price: 1100,
    description: "Prepare for leadership in government and public service organizations with policy and management skills.",
  },
  {
    id: 5,
    slug: "react-js-development",
    title: "React.js Development",
    category: "Technology",
    image: "/images/courses/react.jpg",
    instructor: "Dr. Alex Turner",
    duration: "6 Months",
    students: 350,
    rating: 4.9,
    price: 800,
    description: "Master React.js from fundamentals to advanced patterns including hooks, context, and performance optimization.",
  },
  {
    id: 6,
    slug: "full-stack-development",
    title: "Full Stack Development",
    category: "Technology",
    image: "/images/courses/fullstack.jpg",
    instructor: "Prof. Maria Garcia",
    duration: "1 Year",
    students: 280,
    rating: 4.8,
    price: 1400,
    description: "Become a full stack developer with expertise in Next.js, Node.js, databases, and cloud deployment.",
  },
];

export default courses;
