const events = [
  {
    id: 1,
    slug: "admission-open-2026",
    title: "Admission Open 2026",
    date: "2026-08-15",
    time: "10:00 AM",
    location: "Main Campus, Auditorium Hall",
    image: "/images/events/admission-2026.jpg",
    category: "Admission",
    description: "Join us for the official opening of admissions for the 2026 academic year. Learn about programs, scholarships, and meet faculty.",
  },
  {
    id: 2,
    slug: "science-fair-2026",
    title: "Annual Science Fair 2026",
    date: "2026-09-20",
    time: "9:00 AM",
    location: "Science Block, Ground Floor",
    image: "/images/events/science-fair.jpg",
    category: "Academic",
    description: "Students showcase their innovative research projects. Open to all departments. Prizes for top three projects in each category.",
  },
  {
    id: 3,
    slug: "digital-education-summit",
    title: "Digital Education Summit",
    date: "2026-10-05",
    time: "11:00 AM",
    location: "Conference Center, Room 301",
    image: "/images/events/digital-summit.jpg",
    category: "Conference",
    description: "Leading educators and technology experts gather to discuss the future of digital learning and AI in education.",
  },
  {
    id: 4,
    slug: "learning-network-webinar",
    title: "Learning Network Webinar for Music Teachers",
    date: "2026-07-30",
    time: "3:00 PM",
    location: "Online (Zoom)",
    image: "/images/events/music-webinar.jpg",
    category: "Webinar",
    description: "An interactive online session for music educators to share best practices and discover new teaching methodologies.",
  },
  {
    id: 5,
    slug: "conscious-discipline-summer",
    title: "Conscious Discipline Summer Program",
    date: "2026-07-10",
    time: "8:00 AM",
    location: "Sports Complex",
    image: "/images/events/summer-program.jpg",
    category: "Program",
    description: "A six-week intensive summer program combining academic enrichment with character development and leadership skills.",
  },
];

export default events;
