export const expertTeachersData = [
  {
    id: 101,
    slug: "howard-holmes",
    name: "Howard Holmes",
    role: "Head of Department - EEE",
    avatar: "/images/teacher/expert1.png",
    image: "/images/teacher/expert1.png",
    courses: 12,
    students: 500,
    experience: "20 Years",
    phone: "+880 1711 000001",
    email: "howard.holmes@unisaas.edu",
    bio: "Howard Holmes is the CEO & Founder of Qeducato, bringing over 20 years of experience in educational leadership and institutional development. His vision has shaped the platform into a world-class learning environment, combining innovation with academic excellence. Howard is deeply committed to making quality education accessible to every learner, and his leadership continues to inspire both faculty and students across all departments.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 102,
    slug: "ella-thompson",
    name: "Ella Thompson",
    role: "Head of Department CSE",
    avatar: "/images/teacher/expert2.png",
    image: "/images/teacher/expert2.png",
    courses: 5,
    students: 130,
    experience: "9 Years",
    phone: "+880 1711 000002",
    email: "ella.thompson@unisaas.edu",
    bio: "Ella Thompson is a passionate Early Childhood Education specialist with 9 years of dedicated teaching experience. She believes that the foundation of lifelong learning is built in the earliest years, and her curriculum reflects that philosophy through play-based, inquiry-driven approaches. Ella's warm and nurturing teaching style creates a safe and stimulating environment where young learners can grow with confidence and curiosity.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 103,
    slug: "vincent-cooper",
    name: "Vincent Cooper",
    role: "Head of Department Mathematics",
    avatar: "/images/teacher/expert3.png",
    image: "/images/teacher/expert3.png",
    courses: 6,
    students: 160,
    experience: "11 Years",
    phone: "+880 1711 000003",
    email: "vincent.cooper@unisaas.edu",
    bio: "Vincent Cooper is a Creative Arts & Design educator with 11 years of experience guiding students through the intersection of imagination and technical skill. His courses cover visual communication, digital design, illustration, and design thinking. Vincent encourages students to develop a personal creative voice while mastering industry-standard tools and methodologies. His student-centered approach has produced graduates who are both critically aware and professionally competitive.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 104,
    slug: "danielle-bryant",
    name: "Danielle Bryant",
    role: "Head of Department Civil Eng.",
    avatar: "/images/teacher/expert4.png",
    image: "/images/teacher/expert4.png",
    courses: 4,
    students: 110,
    experience: "8 Years",
    phone: "+880 1711 000004",
    email: "danielle.bryant@unisaas.edu",
    bio: "Danielle Bryant is a Language & Literature educator known for her ability to bring texts to life through critical discussion and creative engagement. With 8 years of teaching experience, she specializes in English literature, academic writing, and communication skills. Danielle fosters a classroom culture where students feel empowered to express ideas clearly and confidently — skills she considers essential for success in any field.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
];