export const expertTeachersData = [
  {
    id: 101,
    slug: "dr-james-anderson",
    name: "Dr. James Anderson",
    role: "Professor & Head, Department of Electrical and Electronic Eng.",
    avatar: "/images/teacher/expert1.png",
    image: "/images/teacher/expert1.png",
    courses: 12,
    students: 500,
    experience: "20 Years",
    phone: "+880 1711 000001",
    email: "j.anderson@qeducato.edu",
    bio: "Dr. James Anderson is a distinguished academic and researcher in Electrical and Electronic Engineering with over two decades of experience in higher education. His expertise spans power systems, renewable energy technologies, and intelligent electrical networks. Known for his student-centered teaching philosophy and commitment to academic excellence, he has supervised numerous research projects and continues to contribute to the advancement of engineering education through innovation and mentorship.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 102,
    slug: "dr-emily-carter",
    name: "Dr. Emily Carter",
    role: "Professor & Head, Department of Computer Science and Engineering",
    avatar: "/images/teacher/expert2.png",
    image: "/images/teacher/expert2.png",
    courses: 5,
    students: 130,
    experience: "9 Years",
    phone: "+880 1711 000002",
    email: "e.carter@qeducato.edu",
    bio: "Dr. Emily Carter is a leading academic in Computer Science and Engineering, specializing in artificial intelligence, data science, and software architecture. With extensive experience in both academia and industry collaboration, she is dedicated to preparing students for the rapidly evolving technological landscape. Her research-driven teaching approach fosters critical thinking, innovation, and practical problem-solving skills among future engineers.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 103,
    slug: "dr-michael-bennett",
    name: "Dr. Michael Bennett",
    role: "Professor & Head, Department of Mathematics",
    avatar: "/images/teacher/expert3.png",
    image: "/images/teacher/expert3.png",
    courses: 6,
    students: 160,
    experience: "11 Years",
    phone: "+880 1711 000003",
    email: "m.bennett@qeducato.edu",
    bio: "Dr. Michael Bennett is a respected mathematician whose academic interests include applied mathematics, statistical modeling, and computational analysis. With more than a decade of teaching and research experience, he is passionate about helping students develop strong analytical and quantitative reasoning skills. His dedication to excellence has earned him recognition for both scholarly contributions and outstanding classroom engagement.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 104,
    slug: "dr-sophia-mitchell",
    name: "Dr. Sophia Mitchell",
    role: "Professor & Head, Department of Civil Engineering",
    avatar: "/images/teacher/expert4.png",
    image: "/images/teacher/expert4.png",
    courses: 4,
    students: 110,
    experience: "8 Years",
    phone: "+880 1711 000004",
    email: "s.mitchell@qeducato.edu",
    bio: "Dr. Sophia Mitchell is an accomplished Civil Engineering educator and researcher with expertise in sustainable infrastructure, structural engineering, and urban development. She is committed to integrating modern engineering practices with real-world applications, enabling students to address contemporary societal challenges. Her leadership, research achievements, and dedication to student success have made her a valued member of the academic community.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
];