// ========================================
// University Faculty Data — SaaS Education Platform
// Faculty Profiles with Department/Subject-based Roles
// ========================================

export const teachersData = [
  {
    id: 1,
    slug: "dr-ahsan-rahman-physics",
    name: "Dr. Ahsan Rahman",
    role: "Physics",
    avatar: "/images/teacher/physics.webp",
    courses: 6,
    students: 180,
    experience: "14 Years",
    phone: "+880 1711 223344",
    email: "ahsan.rahman@unisaas.edu",
    bio: "Dr. Ahsan Rahman is a dedicated Physics faculty member specializing in modern theoretical and applied physics. He focuses on simplifying complex concepts through real-world applications and interactive SaaS-based learning systems designed for higher education.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 2,
    slug: "dr-nabila-karim-chemistry",
    name: "Dr. Nabila Karim",
    role: "Chemistry",
    avatar: "/images/teacher/chemistry.webp",
    courses: 5,
    students: 150,
    experience: "11 Years",
    phone: "+880 1711 223345",
    email: "nabila.karim@unisaas.edu",
    bio: "Dr. Nabila Karim specializes in Organic and Analytical Chemistry. She integrates SaaS-based lab simulations into her teaching to make chemical experiments more accessible and engaging for university students.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 3,
    slug: "prof-mahmud-hasan-economics",
    name: "Prof. Mahmud Hasan",
    role: "Economics",
    avatar: "/images/teacher/economics.webp",
    courses: 4,
    students: 200,
    experience: "16 Years",
    phone: "+880 1711 223346",
    email: "mahmud.hasan@unisaas.edu",
    bio: "Prof. Mahmud Hasan teaches Economics with a strong focus on data-driven decision making, digital economies, and SaaS business models shaping modern global markets.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 4,
    slug: "dr-shaila-ahmed-mathematics",
    name: "Dr. Shaila Ahmed",
    role: "Mathematics",
    avatar: "/images/teacher/mathematics.webp",
    courses: 7,
    students: 220,
    experience: "13 Years",
    phone: "+880 1711 223347",
    email: "shaila.ahmed@unisaas.edu",
    bio: "Dr. Shaila Ahmed is a Mathematics expert focusing on applied calculus, algebra, and computational mathematics, using SaaS-powered visualization tools to enhance student understanding.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 5,
    slug: "dr-imtiaz-khan-biology",
    name: "Dr. Imtiaz Khan",
    role: "Biology",
    avatar: "/images/teacher/biology.webp",
    courses: 5,
    students: 170,
    experience: "10 Years",
    phone: "+880 1711 223348",
    email: "imtiaz.khan@unisaas.edu",
    bio: "Dr. Imtiaz Khan focuses on cellular biology and genetics, integrating SaaS-based virtual labs to help students explore biological systems in an interactive environment.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 6,
    slug: "dr-farzana-ali-biochemistry",
    name: "Dr. Farzana Ali",
    role: "Biochemistry",
    avatar: "/images/teacher/biochemistry.webp",
    courses: 4,
    students: 140,
    experience: "9 Years",
    phone: "+880 1711 223349",
    email: "farzana.ali@unisaas.edu",
    bio: "Dr. Farzana Ali specializes in Biochemistry with a focus on molecular processes and healthcare applications, enhanced through SaaS-based simulation learning systems.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 7,
    slug: "eng-tanvir-hossain-eee",
    name: "Engr. Tanvir Hossain",
    role: "EEE (Electrical & Electronic Engineering)",
    avatar: "/images/teacher/eee.webp",
    courses: 6,
    students: 190,
    experience: "12 Years",
    phone: "+880 1711 223350",
    email: "tanvir.hossain@unisaas.edu",
    bio: "Engr. Tanvir Hossain teaches Electrical and Electronic Engineering with a focus on circuit design, embedded systems, and SaaS-based engineering simulation platforms.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 8,
    slug: "dr-sadia-noor-cse",
    name: "Dr. Sadia Noor",
    role: "CSE (Computer Science & Engineering)",
    avatar: "/images/teacher/cse.webp",
    courses: 8,
    students: 250,
    experience: "11 Years",
    phone: "+880 1711 223351",
    email: "sadia.noor@unisaas.edu",
    bio: "Dr. Sadia Noor is a Computer Science expert specializing in AI, web technologies, and SaaS architecture, preparing students for modern software industries.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 9,
    slug: "eng-rifat-uddin-se",
    name: "Engr. Rifat Uddin",
    role: "SE (Software Engineering)",
    avatar: "/images/teacher/se.webp",
    courses: 6,
    students: 210,
    experience: "10 Years",
    phone: "+880 1711 223352",
    email: "rifat.uddin@unisaas.edu",
    bio: "Engr. Rifat Uddin focuses on Software Engineering principles, SaaS product development, and scalable system architecture used in modern tech industries.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 10,
    slug: "eng-arif-chowdhury-civil",
    name: "Engr. Arif Chowdhury",
    role: "Civil Engineering",
    avatar: "/images/teacher/civil.webp",
    courses: 5,
    students: 160,
    experience: "15 Years",
    phone: "+880 1711 223353",
    email: "arif.chowdhury@unisaas.edu",
    bio: "Engr. Arif Chowdhury is a Civil Engineering specialist focusing on structural design and smart infrastructure planning with SaaS-based modeling tools.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 11,
    slug: "prof-lina-akter-accounting",
    name: "Prof. Lina Akter",
    role: "Accounting",
    avatar: "/images/teacher/accounting.webp",
    courses: 4,
    students: 180,
    experience: "12 Years",
    phone: "+880 1711 223354",
    email: "lina.akter@unisaas.edu",
    bio: "Prof. Lina Akter teaches Accounting and Financial Management with a focus on digital finance systems and SaaS-based accounting solutions for businesses.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 12,
    slug: "dr-samiul-islam-marketing",
    name: "Dr. Samiul Islam",
    role: "Marketing",
    avatar: "/images/teacher/marketing.webp",
    courses: 5,
    students: 230,
    experience: "13 Years",
    phone: "+880 1711 223355",
    email: "samiul.islam@unisaas.edu",
    bio: "Dr. Samiul Islam specializes in Digital Marketing, SaaS growth strategies, and consumer behavior analytics, helping students understand modern business ecosystems.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
];