// ========================================
// University Faculty Data — SaaS Education Platform
// Faculty Profiles with Department/Subject-based Roles
// ========================================

export const teachersData = [
  {
    id: 1,
    slug: "dr-ahsan-rahman-physics",
    name: "Dr. Ahsan Rahman",
    role: "Physics",
    avatar: "/images/teacher/physics.webp",
    courses: 6,
    students: 180,
    experience: "14 Years",
    phone: "+880 1711 223344",
    email: "ahsan.rahman@unisaas.edu",
    bio: "With more than 14 years of teaching experience, Dr. Ahsan Rahman has built a reputation for making Physics both practical and engaging. His classes encourage students to explore how physical laws influence everyday technologies, from renewable energy systems to modern communication devices. He combines theoretical foundations with hands-on problem-solving techniques, helping learners develop strong analytical skills and scientific curiosity. Students appreciate his approachable teaching style, real-world examples, and commitment to creating an interactive learning environment.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 2,
    slug: "dr-nabila-karim-chemistry",
    name: "Dr. Nabila Karim",
    role: "Chemistry",
    avatar: "/images/teacher/chemistry.webp",
    courses: 5,
    students: 150,
    experience: "11 Years",
    phone: "+880 1711 223345",
    email: "nabila.karim@unisaas.edu",
    bio: "Dr. Nabila Karim is an experienced Chemistry educator known for her ability to simplify complex chemical concepts into understandable and engaging lessons. Over the years, she has guided hundreds of students through Organic and Analytical Chemistry while promoting critical thinking and laboratory-based learning. Her teaching emphasizes practical applications, research awareness, and scientific accuracy, helping students gain confidence in both academic and professional settings.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 3,
    slug: "dr-sabina-rahman-economics",
    name: "Dr. Sabina Rahman",
    role: "Economics",
    avatar: "/images/teacher/economics.webp",
    courses: 4,
    students: 200,
    experience: "16 Years",
    phone: "+880 1711 223346",
    email: "sabina.rahman@unisaas.edu",
    bio: "Dr. Sabina Rahman is a dedicated Economics educator with over 16 years of teaching experience, helping students develop a deep understanding of economic principles and their practical applications in the modern world. Her teaching approach combines real-world case studies, analytical thinking, and interactive discussions to make complex economic concepts easy to understand. She specializes in macroeconomics, development economics, digital markets, and contemporary business trends. Known for her supportive mentorship and engaging classroom environment, Dr. Rahman is passionate about preparing students to think critically, solve real-world challenges, and confidently contribute to an increasingly interconnected global economy.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 4,
    slug: "dr-shaila-ahmed-mathematics",
    name: "Dr. Shaila Ahmed",
    role: "Mathematics",
    avatar: "/images/teacher/mathematics.webp",
    courses: 7,
    students: 220,
    experience: "13 Years",
    phone: "+880 1711 223347",
    email: "shaila.ahmed@unisaas.edu",
    bio: "Dr. Shaila Ahmed brings over 13 years of experience in teaching Mathematics at the university level. She is passionate about helping students develop logical reasoning, problem-solving abilities, and confidence in quantitative analysis. Her expertise spans calculus, algebra, statistics, and computational mathematics. Through clear explanations and interactive learning strategies, she makes challenging mathematical concepts accessible to learners from diverse academic backgrounds.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 5,
    slug: "dr-imtiaz-khan-biology",
    name: "Dr. Imtiaz Khan",
    role: "Biology",
    avatar: "/images/teacher/biology.webp",
    courses: 5,
    students: 170,
    experience: "10 Years",
    phone: "+880 1711 223348",
    email: "imtiaz.khan@unisaas.edu",
    bio: "Dr. Imtiaz Khan is a Biology faculty member with extensive experience in cellular biology, genetics, and life sciences education. He believes that understanding biological systems requires curiosity, observation, and practical exploration. His classes often connect scientific theories with real-world biological phenomena, enabling students to appreciate the relevance of biology in healthcare, environmental studies, and modern research.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 6,
    slug: "dr-farzana-ali-biochemistry",
    name: "Dr. Farzana Ali",
    role: "Biochemistry",
    avatar: "/images/teacher/biochemistry.webp",
    courses: 4,
    students: 140,
    experience: "9 Years",
    phone: "+880 1711 223349",
    email: "farzana.ali@unisaas.edu",
    bio: "Dr. Farzana Ali specializes in Biochemistry and has spent nearly a decade helping students understand the molecular processes that drive living organisms. Her teaching combines scientific depth with practical relevance, particularly in areas related to healthcare, nutrition, and biotechnology. Students value her supportive approach, attention to detail, and ability to explain advanced biochemical concepts in a clear and relatable manner.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 7,
    slug: "eng-tanvir-hossain-eee",
    name: "Engr. Tanvir Hossain",
    role: "EEE (Electrical & Electronic Engineering)",
    avatar: "/images/teacher/eee.webp",
    courses: 6,
    students: 190,
    experience: "12 Years",
    phone: "+880 1711 223350",
    email: "tanvir.hossain@unisaas.edu",
    bio: "Engr. Tanvir Hossain is an accomplished Electrical and Electronic Engineering educator with expertise in circuit analysis, embedded systems, and modern electronics. He focuses on bridging the gap between classroom learning and industry practices, preparing students to solve engineering challenges with confidence. His courses emphasize innovation, practical design skills, and the latest technological developments shaping the engineering sector.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 8,
    slug: "dr-sadia-noor-cse",
    name: "Dr. Sadia Noor",
    role: "CSE (Computer Science & Engineering)",
    avatar: "/images/teacher/cse.webp",
    courses: 8,
    students: 250,
    experience: "11 Years",
    phone: "+880 1711 223351",
    email: "sadia.noor@unisaas.edu",
    bio: "Dr. Sadia Noor is a Computer Science educator with a strong passion for emerging technologies, software development, and artificial intelligence. Throughout her teaching career, she has helped students build both technical expertise and problem-solving capabilities required in today's digital economy. Her classes encourage creativity, collaboration, and hands-on learning while exploring modern computing concepts and industry trends.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 9,
    slug: "eng-rifat-uddin-se",
    name: "Engr. Rifat Uddin",
    role: "SE (Software Engineering)",
    avatar: "/images/teacher/se.webp",
    courses: 6,
    students: 210,
    experience: "10 Years",
    phone: "+880 1711 223352",
    email: "rifat.uddin@unisaas.edu",
    bio: "Engr. Rifat Uddin has dedicated his career to teaching Software Engineering and guiding students through the principles of building reliable, scalable, and maintainable software systems. His academic approach blends software design, project management, and real-world development practices. Students benefit from his industry-oriented perspective and practical insights into modern software development workflows.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 10,
    slug: "eng-arif-chowdhury-civil",
    name: "Engr. Arif Chowdhury",
    role: "Civil Engineering",
    avatar: "/images/teacher/civil.webp",
    courses: 5,
    students: 160,
    experience: "15 Years",
    phone: "+880 1711 223353",
    email: "arif.chowdhury@unisaas.edu",
    bio: "With over 15 years of experience in Civil Engineering education, Engr. Arif Chowdhury is committed to preparing future engineers for the challenges of infrastructure development and urban planning. His expertise includes structural engineering, construction management, and sustainable design practices. He encourages students to think critically about how engineering solutions can improve communities and support long-term development goals.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 11,
    slug: "prof-lina-akter-accounting",
    name: "Prof. Lina Akter",
    role: "Accounting",
    avatar: "/images/teacher/accounting.webp",
    courses: 4,
    students: 180,
    experience: "12 Years",
    phone: "+880 1711 223354",
    email: "lina.akter@unisaas.edu",
    bio: "Prof. Lina Akter is a respected Accounting and Finance educator with extensive experience in financial reporting, business management, and corporate accounting practices. She helps students understand how financial information supports effective decision-making in organizations. Her teaching style combines theoretical knowledge with practical business scenarios, ensuring students develop both technical competence and professional confidence.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
  {
    id: 12,
    slug: "dr-samima-islam-marketing",
    name: "Dr. Samima Islam",
    role: "Marketing",
    avatar: "/images/teacher/marketing.webp",
    courses: 5,
    students: 230,
    experience: "13 Years",
    phone: "+880 1711 223355",
    email: "samima.islam@unisaas.edu",
    bio: "Dr. Samima Islam is a Marketing specialist with more than a decade of experience teaching consumer behavior, brand management, and digital marketing strategies. She is passionate about helping students understand how businesses connect with audiences in an increasingly competitive marketplace. Through case studies, market analysis, and real-world examples, she prepares learners to think creatively and make data-informed marketing decisions.",
    social: { facebook: "#", instagram: "#", twitter: "#" },
  },
];
