export const galleryCategories = [
  { id: "all", label: "All" },
  { id: "campus-life", label: "Campus Life" },
  { id: "events", label: "Events" },
  { id: "academics", label: "Academics" },
  { id: "sports", label: "Sports" },
  { id: "clubs", label: "Clubs" },
  { id: "research", label: "Research" },
  { id: "graduation", label: "Graduation" },
];

export const galleryData = [
  {
    id: 1,
    title: "Beautiful Campus",
    description:
      "Discover our green and modern campus from above. Spanning 120 acres of landscaped grounds, our campus blends contemporary architecture with natural beauty.",
    category: "campus-life",
    photoCount: 45,
    date: "March 2024",
    location: "Main Campus, Qeducato University",
    image: "/images/gallery/campus-aerial.jpg",
    featured: true,
    size: "large",
    images: [
      "/images/gallery/campus-aerial.jpg",
      "/images/gallery/campus-2.jpg",
      "/images/gallery/campus-3.jpg",
    ],
  },
  {
    id: 2,
    title: "Convocation 2024",
    description:
      "A landmark day for Class of 2024. Over 1,200 graduates received their degrees in a ceremony full of pride, joy, and tradition.",
    category: "graduation",
    photoCount: 38,
    date: "May 2024",
    location: "Grand Auditorium, Qeducato University",
    image: "/images/gallery/convocation.jpg",
    featured: true,
    size: "medium",
    images: [
      "/images/gallery/convocation.jpg",
      "/images/gallery/convocation-2.jpg",
    ],
  },
  {
    id: 3,
    title: "Library Moments",
    description:
      "Quiet corners and curious minds. Our library hosts over 500,000 volumes and remains the heart of intellectual life on campus.",
    category: "academics",
    photoCount: 21,
    date: "February 2024",
    location: "Central Library, Block C",
    image: "/images/gallery/library.jpg",
    featured: true,
    size: "medium",
    images: ["/images/gallery/library.jpg", "/images/gallery/library-2.jpg"],
  },
  {
    id: 4,
    title: "Student Life",
    description:
      "Friendships forged on the lawns. Campus social life brings together students from 40+ countries in shared moments of learning and laughter.",
    category: "campus-life",
    photoCount: 32,
    date: "April 2024",
    location: "Central Lawn, Qeducato University",
    image: "/images/gallery/student-life.jpg",
    featured: true,
    size: "medium",
    images: [
      "/images/gallery/student-life.jpg",
      "/images/gallery/student-life-2.jpg",
    ],
  },
  {
    id: 5,
    title: "Research & Labs",
    description:
      "Pushing the boundaries of what's known. Our labs are equipped with state-of-the-art instruments for biology, chemistry, and materials science.",
    category: "research",
    photoCount: 27,
    date: "January 2024",
    location: "Science & Research Wing",
    image: "/images/gallery/research.jpg",
    featured: true,
    size: "medium",
    images: ["/images/gallery/research.jpg"],
  },
  {
    id: 6,
    title: "Sports Events",
    description:
      "Where champions are made. Our inter-university sports meet drew athletes from 18 universities across the region.",
    category: "sports",
    photoCount: 19,
    date: "March 2024",
    location: "Qeducato Sports Complex",
    image: "/images/gallery/sports.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/sports.jpg"],
  },
  {
    id: 7,
    title: "Annual Fest",
    description:
      "Three nights of music, art, and culture. Annual Fest 2024 broke attendance records with over 8,000 attendees.",
    category: "events",
    photoCount: 29,
    date: "November 2024",
    location: "Outdoor Amphitheatre",
    image: "/images/gallery/annual-fest.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/annual-fest.jpg"],
  },
  {
    id: 8,
    title: "Cultural Programs",
    description:
      "Heritage alive on stage. Our cultural diversity week celebrates traditions from over 30 countries represented in our student body.",
    category: "events",
    photoCount: 16,
    date: "October 2024",
    location: "Main Stage, Cultural Center",
    image: "/images/gallery/cultural.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/cultural.jpg"],
  },
  {
    id: 9,
    title: "Clubs & Activities",
    description:
      "Over 60 student-run clubs. From robotics to poetry — find your people, build something meaningful.",
    category: "clubs",
    photoCount: 14,
    date: "September 2024",
    location: "Student Activity Hub",
    image: "/images/gallery/clubs.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/clubs.jpg"],
  },
  {
    id: 10,
    title: "Orientation Week",
    description:
      "The beginning of everything. Welcome Week 2024 welcomed 1,800 new students to Qeducato's community.",
    category: "campus-life",
    photoCount: 33,
    date: "August 2024",
    location: "Welcome Plaza",
    image: "/images/gallery/orientation.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/orientation.jpg"],
  },
  {
    id: 11,
    title: "Tech Symposium",
    description:
      "Industry meets academia. Speakers from Google, Meta, and local startups joined students for a day of talks and workshops.",
    category: "academics",
    photoCount: 22,
    date: "December 2024",
    location: "Engineering Block Auditorium",
    image: "/images/gallery/symposium.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/symposium.jpg"],
  },
  {
    id: 12,
    title: "Inter-College Debate",
    description:
      "Minds sharpened through argument. Our debate society hosted 24 teams in the annual national inter-college championship.",
    category: "clubs",
    photoCount: 11,
    date: "November 2024",
    location: "Debate Hall, Block B",
    image: "/images/gallery/debate.jpg",
    featured: false,
    size: "small",
    images: ["/images/gallery/debate.jpg"],
  },
];